language: php
php:
  - 7.0
  - 7.1
before_install:
  - composer self-update
  - composer create-project --prefer-dist laravel/laravel nitseditor
  - cd ./nitseditor
  - composer config repositories.noeticitservices vcs https://github.com/noeticit/Nitseditor_Plugin_Dev.git
  - composer require noeticitservices/plugindev dev-master
  - composer update
  - cp ./vendor/noeticitservices/plugindev/tests/config/.env ./
  - rm ./config/app.php
  - cp ./vendor/noeticitservices/plugindev/tests/config/app.php ./config
  - php artisan vendor:publish --provider=Nitseditor\System\Providers\NitsEditorServiceProvider
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - php artisan migrate
  - cd ./vendor/noeticitservices/plugindev

script: "phpunit"